apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets
  namespace: ai
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-ai
    namespace: flux-system
  path: ./infrastructure/secrets
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mcp-github
  namespace: ai
spec:
  dependsOn:
    - name: secrets
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-ai
    namespace: flux-system
  path: ./infrastructure/mcp-github
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mcp-grafana
  namespace: ai
spec:
  dependsOn:
    - name: prometheus
      namespace: flux-system
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-ai
    namespace: flux-system
  path: ./infrastructure/mcp-grafana
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mcp-kubernetes
  namespace: ai
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-ai
    namespace: flux-system
  path: ./infrastructure/mcp-kubernetes
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mcp-photoprism-mmontes
  namespace: ai
spec:
  dependsOn:
    - name: mariadb-mmontes
      namespace: media
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-ai
    namespace: flux-system
  path: ./infrastructure/mcp-photoprism-mmontes
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mcp-photoprism-xiaowen
  namespace: ai
spec:
  dependsOn:
    - name: mariadb-xiaowen
      namespace: media
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-ai
    namespace: flux-system
  path: ./infrastructure/mcp-photoprism-xiaowen
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: llamacpp
  namespace: ai
spec:
  dependsOn:
    - name: secrets
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-ai
    namespace: flux-system
  path: ./infrastructure/llamacpp
  prune: true
  timeout: 5m
---
# CUDA Out of Memory when deploying Qwen3.5-35B-A3B-NVFP4 
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: vllm
#   namespace: ai
# spec:
#   dependsOn:
#     - name: secrets
#   interval: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-tenant-ai
#     namespace: flux-system
#   path: ./infrastructure/vllm
#   prune: true
#   timeout: 5m
# ---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kserve-crds
  namespace: ai
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-ai
    namespace: flux-system
  path: ./infrastructure/kserve/crds
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kserve-config
  namespace: ai
spec:
  dependsOn:
    - name: secrets
    - name: kserve-crds
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-ai
    namespace: flux-system
  path: ./infrastructure/kserve/config
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kserve-resources
  namespace: ai
spec:
  dependsOn:
    - name: kserve-config
    - name: cert-manager-crds
      namespace: flux-system
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-ai
    namespace: flux-system
  path: ./infrastructure/kserve/resources
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kserve-llmisvc-resources
  namespace: ai
spec:
  dependsOn:
    - name: kserve-config
    - name: cert-manager-crds
      namespace: flux-system
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-ai
    namespace: flux-system
  path: ./infrastructure/kserve/llmisvc-resources
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kserve-localmodel-resources
  namespace: ai
spec:
  dependsOn:
    - name: kserve-crds
    - name: cert-manager-crds
      namespace: flux-system
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-ai
    namespace: flux-system
  path: ./infrastructure/kserve/localmodel-resources
  prune: true
  timeout: 5m
---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: kserve-models
#   namespace: ai
# spec:
#   dependsOn:
#     - name: kserve-resources
#     - name: kserve-llmisvc-resources
#     - name: kserve-localmodel-resources
#   interval: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-tenant-ai
#     namespace: flux-system
#   path: ./infrastructure/kserve/models
#   prune: true
#   timeout: 10m
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: lws
#   namespace: ai
# spec:
#   interval: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-tenant-ai
#     namespace: flux-system
#   path: ./infrastructure/lws
#   prune: true
#   timeout: 5m