apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: huggingface
  namespace: ai
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-ai
    namespace: flux-system
  path: ./infrastructure/huggingface
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: github
  namespace: ai
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-ai
    namespace: flux-system
  path: ./infrastructure/github
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ollama
  namespace: ai
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-ai
    namespace: flux-system
  path: ./infrastructure/ollama
  prune: true
  timeout: 5m
---
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mcp-github
  namespace: ai
spec:
  dependsOn:
    - name: github
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-ai
    namespace: flux-system
  path: ./infrastructure/mcp-github
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mcp-grafana
  namespace: ai
spec:
  dependsOn:
    - name: prometheus
      namespace: flux-system
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-ai
    namespace: flux-system
  path: ./infrastructure/mcp-grafana
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mcp-kubernetes
  namespace: ai
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-ai
    namespace: flux-system
  path: ./infrastructure/mcp-kubernetes
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mcp-photoprism-mmontes
  namespace: ai
spec:
  dependsOn:
    - name: mariadb-mmontes
      namespace: media
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-ai
    namespace: flux-system
  path: ./infrastructure/mcp-photoprism-mmontes
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mcp-photoprism-xiaowen
  namespace: ai
spec:
  dependsOn:
    - name: mariadb-xiaowen
      namespace: media
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-ai
    namespace: flux-system
  path: ./infrastructure/mcp-photoprism-xiaowen
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: workspace
  namespace: ai
spec:
  dependsOn:
    - name: github
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-ai
    namespace: flux-system
  path: ./infrastructure/workspace
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: llama-qwen35-35b
  namespace: ai
spec:
  dependsOn:
    - name: huggingface
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-ai
    namespace: flux-system
  path: ./infrastructure/llama-qwen35-35b
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: llama-qwen35-35b-3q
  namespace: ai
spec:
  dependsOn:
    - name: huggingface
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-ai
    namespace: flux-system
  path: ./infrastructure/llama-qwen35-35b-q3
  prune: true
  timeout: 5m
---
# CUDA Out of Memory when deploying Qwen3.5-35B-A3B-NVFP4 
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: vllm
#   namespace: ai
# spec:
#   dependsOn:
#     - name: huggingface
#   interval: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-tenant-ai
#     namespace: flux-system
#   path: ./infrastructure/vllm
#   prune: true
#   timeout: 5m
# ---
# TODO: LLMInferenceServices to use models cached using LocalModelCache
# See:
# https://kserve.github.io/website/docs/install/localmodel-install#prerequisites
# https://github.com/kserve/kserve/issues/5116
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: kserve-crds
#   namespace: kserve
# spec:
#   interval: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-tenant-ai
#     namespace: flux-system
#   path: ./infrastructure/kserve/crds
#   prune: true
#   timeout: 5m
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: kserve-config
#   namespace: kserve
# spec:
#   dependsOn:
#     - name: huggingface
#     - name: kserve-crds
#   interval: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-tenant-ai
#     namespace: flux-system
#   path: ./infrastructure/kserve/config
#   prune: true
#   timeout: 5m
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: kserve-resources
#   namespace: kserve
# spec:
#   dependsOn:
#     - name: kserve-config
#     - name: cert-manager-crds
#       namespace: flux-system
#   interval: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-tenant-ai
#     namespace: flux-system
#   path: ./infrastructure/kserve/kserve-resources
#   prune: true
#   timeout: 5m
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: kserve-llmisvc-resources
#   namespace: kserve
# spec:
#   dependsOn:
#     - name: kserve-config
#     - name: lws
#       namespace: ai
#     - name: cert-manager-crds
#       namespace: flux-system
#   interval: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-tenant-ai
#     namespace: flux-system
#   path: ./infrastructure/kserve/kserve-llmisvc-resources
#   prune: true
#   timeout: 5m
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: lws
#   namespace: ai
# spec:
#   interval: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-tenant-ai
#     namespace: flux-system
#   path: ./infrastructure/lws
#   prune: true
#   timeout: 5m