apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ollama
  namespace: ai
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-ai
    namespace: flux-system
  path: ./infrastructure/ollama
  prune: true
  timeout: 5m