---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-token
  namespace: ai
spec:
  encryptedData:
    GITHUB_TOKEN: AgCd/rads9IPph1pVmFEyuDWwB0zZrREj5Eim0QQVbdl1nsHnYjfV/YwjDuOeHAslA5PgRLK51UtPbomHZcYCirH3bZ+MU0N4mCoVBSJDxwfXeIixswGWnkOmpFSJg24WU6VNOh75ob6KZXqIRSWmJPxo3TgWqBlBou1Dwzxxs15j8m57/cRjZOc/gJ50L4060kxmA0pZkMf5h4c1lFWGTJJuq+0qMQ3+Dnm/bMScTX1QulESCzZSsf31dYDxSpd9R/4Waond+Ospk2LzSDYKnRNNN9EWPuLZFC8Yem5CaUD4prPX9nl46JvlQUDVy+Aeos+jbdDzlnBx2Szn67wShvy9cwMiiNdMkPvwvXA6e/kX8aQdA3+ewv3NRS07Ldt1O315+m/6jpspf3xQIypN5f7MBQMlSsBx2YZ0ipMb5sthzeuAcu4kpxYqKLinB5tcPqk1AQxuuG5hvNDEOTFiShTGbPEzQ2XPLf8o2on333jJeLvGZU4P4vnGkYcRDkD7WZ9d+SM+et7ffBwJNL+TYv5hhOJYHkmhWWOj8SqLO0UW8zjKSfaXxuqAyOgpJTUtFi0dMMj1f7pRuPs55r0bkINlyPXu18vVXFEy6tBZpnTn/keF2ABct/fEoJ4C/2DfimQJm/ZHRo/lybmJZRj6WozFgtOUEbsCDqO42ZTJS8qq7o8U/zl+GhceBWWHQts7Wdk+/4SBcssNgdCe8HVrrb3kf9MmqXLR+aZj40HQaWldSsaETxIOG/O
  template:
    metadata:
      creationTimestamp: null
      name: github-token
      namespace: ai
