apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - opencode-httproute.yaml
  - restic-workspace-sealedsecret.yaml
  - workspace-pvc.yaml
  - workspace-replicationdestination.yaml
  - workspace-replicationsource.yaml
  - workspace-service.yaml
  - workspace-statefulset.yaml
