apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-storage-workspace-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: topolvm