apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workspace
  template:
    metadata:
      labels:
        app: workspace
    spec:
      securityContext:
        fsGroup: 1111
      runtimeClassName: nvidia
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.present
                operator: Exists
      tolerations:
      - effect: NoSchedule
        key: node.mmontes.io/type
        value: compute-xlarge
      initContainers:
        - name: sync
          image: ghcr.io/mmontes11/ai-workspace:0.2.0
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -e
              if [ $(ls -A /home/mmontes | grep -v "lost+found" | wc -l) -eq 0 ]; then
                echo "PVC is empty. Initializing home directory from template..."
                rsync -av /opt/template/ /home/mmontes/
              fi
              echo "Sync complete."
          volumeMounts:
            - name: home-storage
              mountPath: /home/mmontes
      containers:
        - name: workspace
          image: ghcr.io/mmontes11/ai-workspace:0.1.0
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              memory: "8Gi"
              nvidia.com/gpu: 1
          ports:
            - containerPort: 4096
          volumeMounts:
            - name: home-storage
              mountPath: /home/mmontes
      volumes:
        - name: home-storage
          persistentVolumeClaim:
            claimName: workspace