apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - llama-qwen35-35b-httproute.yaml
  - llama-qwen35-35b-service.yaml
  - llama-qwen35-35b-servicemonitor.yaml
  - llama-qwen35-35b-statefulset.yaml