apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: llama-qwen35-35b
spec:
  parentRefs:
    - name: traefik-internal
      namespace: networking
  hostnames:
    - "llama-qwen35-35b.mmontes-internal.duckdns.org"
  rules:
    - backendRefs:
        - name: llama-qwen35-35b
          port: 8080