apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mcp-grafana
spec:
  chart:
    spec:
      chart: grafana-mcp
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: "0.2.2"
  interval: 1h0m0s
  values:
    fullnameOverride: mcp-grafana
    grafana:
      url: "http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local"
      apiKeySecret:
        name: mcp-grafana
        key: token
    extraArgs:
      - --disable-write
      - --debug
      - --log-level
      - debug
    env:
       GRAFANA_ORG_ID: "1"