apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mcp-grafana
spec:
  chart:
    spec:
      chart: grafana-mcp
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: "0.2.2"
  interval: 1h0m0s
  values:
    fullnameOverride: mcp-grafana
    grafana:
      url: "http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local"
      apiKeySecret:
        name: mcp-grafana
        key: token
    extraArgs:
      - --address
      - localhost:8000
      - -t
      - sse
      - --disable-write
      - --debug
      - --log-level
      - debug
    env:
       GRAFANA_ORG_ID: "1"
    extraContainers:
      - name: mcpo
        image: ghcr.io/open-webui/mcpo:main
        command:
          - sh
          - -c
          - |
            echo "mcpo: sleeping 10s to wait for grafana mcp server..."
            sleep infinity
        ports:
          - containerPort: 9000
            name: mcpo
    service:
      port: 8000
      extraPorts:
        - port: 9000
          targetPort: mcpo
          protocol: TCP
          name: mcpo
