apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - llama-qwen35-35b-ctx256k-httproute.yaml
  - llama-qwen35-35b-ctx256k-service.yaml
  - llama-qwen35-35b-ctx256k-servicemonitor.yaml
  - llama-qwen35-35b-ctx256k-statefulset.yaml