apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
spec:
  chartRef:
    kind: OCIRepository
    name: n8n
  interval: 10m
  values:
    queueMode:
      enabled: false
    database:
      type: sqlite
      useExternal: false
    redis:
      enabled: false
    persistence:
      enabled: true
      size: 5Gi
      storageClass: rook-ceph
    config:
      extraEnv:
        - name: N8N_EDITOR_BASE_URL
          value: "https://n8n.mmontes-internal.duckdns.org"
        - name: N8N_TRUST_PROXY
          value: "1"
        - name: N8N_PROXY_HOPS
          value: "1"
    secretRefs:
      existingSecret: n8n
    service:
      type: ClusterIP
      port: 5678