apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-secrets
spec:
  encryptedData:
    - N8N_ENCRYPTION_KEY: <ENCRYPTED_KEY>
    - N8N_HOST: <ENCRYPTED_HOST>
    - N8N_PORT: <ENCRYPTED_PORT>
    - N8N_PROTOCOL: <ENCRYPTED_PROTOCOL>
  template:
    metadata:
      name: n8n-secrets
    type: Opaque
