apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-models
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  storageClassName: topolvm
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-user
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: topolvm
