apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - kserve-llmisvc-resources-helmrelease.yaml
  - kserve-llmisvc-resources-ocirepository.yaml
  - kserve-resources-helmrelease.yaml
  - kserve-resources-ocirepository.yaml
  - kserve-runtime-configs-helmrelease.yaml
  - kserve-runtime-configs-ocirepository.yaml
