apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vllm
spec:
  chart:
    spec:
      chart: vllm-stack
      sourceRef:
        kind: HelmRepository
        name: vllm
      version: "0.1.10"
  interval: 1h0m0s
  values:
    servingEngineSpec:
      enableEngine: true
      strategy:
        type: Recreate
      runtimeClassName: nvidia
      tolerations:
      - effect: NoSchedule
        key: node.mmontes.io/type
        value: compute-xlarge
      serviceMonitor:
        enabled: true
      imagePullPolicy: "IfNotPresent"

      modelSpec:
        # - name: opt-125m
        #   repository: vllm/vllm-openai
        #   tag: cu130-nightly

        #   modelURL: facebook/opt-125m
        #   hf_token:
        #     secretName: hf-token
        #     secretKey: HF_TOKEN

        #   vllmConfig:
        #     extraArgs:
        #       - --enable-sleep-mode

        #   env:
        #     - name: VLLM_SERVER_DEV_MODE
        #       value: "1"

        #   replicaCount: 1
        #   requestGPU: 1
        #   requestCPU: 1
        #   requestMemory: 4Gi

        #   pvcStorage: 5Gi
        #   pvcAccessMode:
        #     - ReadWriteOnce
        #   storageClass: topolvm

        #   affinity:
        #     nodeAffinity:
        #       requiredDuringSchedulingIgnoredDuringExecution:
        #         nodeSelectorTerms:
        #         - matchExpressions:
        #           - key: nvidia.com/gpu.present
        #             operator: Exists

        - name: qwen35-35b
          repository: vllm/vllm-openai
          tag: cu130-nightly

          modelURL: /data
          hf_token:
            secretName: hf-token
            secretKey: HF_TOKEN
      
          initContainer:
            name: init
            image: vllm/vllm-openai:cu130-nightly
            command:
              - bash
              - -c
            args:
              - hf download Sehyo/Qwen3.5-35B-A3B-NVFP4 --local-dir /data
            mountPvcStorage: true
            resources:
              requests:
                cpu: 4
                memory: 2Gi

          vllmConfig:
            enablePrefixCaching: true
            enableChunkedPrefill: true
            maxModelLen: 2048
            gpuMemoryUtilization: 0.75
            extraArgs:
              - --served-model-name=qwen35-35B
              - --enforce-eager
              - --language-model-only
              - --kv-cache-dtype=fp8
              - --reasoning-parser=qwen3
              - --enable-auto-tool-choice 
              - --tool-call-parser=qwen3_coder
              - --enable-sleep-mode
          env:
            - name: VLLM_LOGGING_LEVEL
              value: DEBUG
            - name: VLLM_SERVER_DEV_MODE
              value: "1"

          replicaCount: 1
          requestGPU: 1
          requestCPU: 4
          requestMemory: 16Gi

          pvcStorage: 100Gi
          pvcAccessMode:
            - ReadWriteOnce
          storageClass: topolvm

          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: nvidia.com/gpu.present
                    operator: Exists

    routerSpec:
      enableRouter: true
      repository: "lmcache/lmstack-router"
      tag: "v0.1.10"
      imagePullPolicy: "IfNotPresent"
      resources:
        requests:
          cpu: 500m
          memory: 500Mi
        limits:
          memory: 1Gi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.mmontes.io/type
                operator: In
                values:
                - compute-large
      # tolerations not supported, added via postRenderers
      # see: https://github.com/vllm-project/production-stack/blob/c5eb8dc21c7f81bfc2ee9f7cf74e82f206fe5776/helm/templates/deployment-router.yaml#L36
      # tolerations:
      # - effect: NoSchedule
      #   key: node.mmontes.io/type
      #   value: compute-large
      serviceMonitor:
        enabled: true
      route:
        main:
          enabled: true
          parentRefs:
            - name: traefik-internal
              namespace: networking
          hostnames:
            - vllm.mmontes-internal.duckdns.org

  postRenderers:
    - kustomize:
        patches:
          # this is to avoid the following error logs in vllm:
          # (APIServer pid=1) WARNING 03-22 14:24:51 [envs.py:1730] Unknown vLLM environment variable detected: VLLM_O
          - target:
              kind: Deployment
              labelSelector: "app.kubernetes.io/component=serving-engine"
            patch: |
              - op: add
                path: /spec/template/spec/enableServiceLinks
                value: false
          # tolerations not supported in router
          # see: https://github.com/vllm-project/production-stack/blob/c5eb8dc21c7f81bfc2ee9f7cf74e82f206fe5776/helm/templates/deployment-router.yaml#L36
          - target:
              kind: Deployment
              name: vllm-deployment-router
            patch: |
              - op: add
                path: /spec/template/spec/tolerations
                value:
                  - effect: NoSchedule
                    key: node.mmontes.io/type
                    value: compute-large