---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gh-token
  namespace: ai
spec:
  encryptedData:
    GITHUB_TOKEN: AgCEVFW4BZMAdvU9hYKnTtmPmexnTfoiwrUnK6S4u2seR283/5E57B3zVilGAYHyMKPXxZJbmu9pv57ENqZfGM/83oM1AvSbAlN2AgW25OweXJCERE4DBWKqwXeAmbsDwAiXyB77O+3dXGRVWBhNiaVxaYIHPCvUWNF9zsUKSu/U2ymNhVm8TfKg/PcmqNmHQryth9KLb61PxZJk1Tst8skZwlpDp32Fx9J+mV9dboDs8WEBDPQVXyX22bdwjq9p3XgIwPAXkjtbPRYFCekbUBUME6M6Rzy+Iqgzzgzkm1f3/rCnV0TMpXhWNrdVp+z51WAugt/DsfcLinpnOJwaaHIRyK4JCtc3ELhhX6QFJnqd+iJJDRcXemXkyUYPvyp5mVqaKeWPhD9D4Jn3KyGj9kBTGJd1cdf7vyO3UgTgQGwhtVd1WD1Z1376wukkNK8hhkPxqPVt+Z+rJGSp9JYeHMArTzaB94cfqgHUiIHBhakXCy3mrbZMnU2VPag9UigX+kY4j/uv1C7qWE1hTM2G7IjG27NUY6SCaGYIx4DlTPXXtNrdRaDarHXdbH0J/Fk1oMLXryD4vS3DrRZclgYYoC5Wd5V0o2LoV2uNRTtiJ7oYr8yUSov9nI/Y5rkGzyPgr3Mr0U99PjwIr0oS2dU8OZdLti7eop99mpRt1rJdu0ljLYrOyO4Okv2oy6eeNdhIQ0tbfYTAjn0xo+COT0EqPYa/rovZkjG3zepq/RP1pLVrYAoiq1CPxjjUaJzHoOPSk8HWfGYIt5UtnZbI8opIrpMYzPWXfFPc04j6DLdEC3urfG9FKoIYZ2lL9hMYX5M=
  template:
    metadata:
      creationTimestamp: null
      name: gh-token
      namespace: ai
