---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gh-token-mariadb-operator
  namespace: ai
spec:
  encryptedData:
    GITHUB_TOKEN: AgCqyKDe9AWVtX9F20A+Co7SzHyMjzwQjhEmbIxzAYmvinAZUPVw0+WgW7dnEcfZ0ofl+8S9iEzwHvF1ssUVrhwE+Bp2V/7OlksEMe2/PT5LwLEup9R6RZIRSajyQawPecdyG+kE5UtA5zb8FpMw7DYPvtTRUpz+foXrDHKafnXlJ0XYMdkJ6Fi6L1SIJkcjxmU/IRKufdBgz09ZcI/4hyYUC0dvjvnwzuNlGpHggF2Z7ONy2FC6OTSia/FG+9+gI6WOYAawVFPVoii96aFBKk1+K5LQMltRhLLhfzNGNe3rdqGv9mAyiILqTioSWIpFiOjhsKNsUXkL0RaqlT5fkJllB4ZUK055Qfe96BAji/q+b9ToasFs48wf/nH71sOYW34izbDNZn/OyRRUMaUVUzZGhTsDMwdOCJ9TtwH0Wc0we6UesvVgvekLtscd+OKhHkiQFnllCRCwD1MaziOELedVN5OlSOdnzRwwr61vIQorlcxZe0NkWBG2BSNdwXGZ4byDpF2kKVS9zfsz1eYGYOYxdXuEif3PImjYNrtOa6FDfN/Gycvf7/rwP7E/f6dYq+W1+/D9JvAz0LLj4WZ/Ni8vKAnscy4tc6ffzgPNSW2W9Wn4Vgb0JeC3C8WggYYsBU4++4iC3VRWJ9u1H6re3O/7TI3L3MWlflaX41uCl2LG8ZBkvhxkdNrVhamfhu67gL9roo35upyaMtq1HUYs9X4PFU6Lc1SE0HU7a0fT6DkGxLzRAGmgQz2cXc8/+Epj7vzOBpvlTP5QmjmRU+2viowrmk22doxOjX7TrN1/ByfoNVexjiAc/o2DLcEN+gQ=
  template:
    metadata:
      name: gh-token-mariadb-operator
      namespace: ai
    type: Opaque
