---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gh-token-mariadb-operator
  namespace: ai
spec:
  encryptedData:
    GITHUB_TOKEN: AgCqd6wUCWgq1pvw15ODqJ6LMxGAazJT66oK1f+0ah2wEx9S/FWb8RXuq0fJl4f3l1ncG1CVYli+7lyZ7mBcVKnUB57O3a+Su75BYcXGubSKHm/dfr6lH6kwNX8mTOumc4NUyG76QO4pAizUVtwSk9VAQjO9+6P64jgP/pc3Zm+HSo3Qfg9dKQMAjuPrtNzvpFrT5KpKptgp4Kpb12Z3pF9R3wOKRSKAGFOHosZOmNsHUzqkEI3pbLVz6McIWgo+wf3mQFmum+Btq91Z1PT0/1etU5WuMPJ95xKj+kbhsqeqDFhMQPJnefT/w2eU36zjztz1qZQR1Wt5uMPog+vLCwtsahKFR4qnXb0T43gbIWxN15hasGndgrPrJP0yTbUwrFqhG3WRUG0bTpRY+X3S5sbg/a0FH1vg0tt6IB6XiHutBGfKJTAjJVkPHwkPQk4stOHvxjX8B1Sd3WSjy9m+8AhZwpwLa67ldupJNzoaeZPWYvcZcIjMeKSmyrjQ0/JLsyf7/79Xv8PIstIlBD2RG2xG8HpQ0lEgcSOAjVJMxF9hPctdDEbGZBMlnvN2+5fpY4JYVTsR0B9sNCUSBj00P0NVErRE/Y7+AWVxaCE1/GED+RNnw58iyovsKbhBP+GYF379++OaVC+mzL0b/h5jGwwurYOsjp1rFwtNxcins4ZE1P1hq8R9eN9mq4FaGG74p597mbwxDM/eZR5QUo9yjJa+A0KZe2yiI+u6VfKvffmxD7b0aibBH0FkVmR1t8lipQXX8HC7AvbRVtZuCjkt3ZjtNeKuesY6n7pb6bZtNVPpsED7I91XfbvPU8LC63I=
  template:
    metadata:
      name: gh-token-mariadb-operator
      namespace: ai
    type: Opaque
