---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: multica-token
  namespace: ai
spec:
  encryptedData:
    MULTICA_TOKEN: AgB7Y1m3BcCA26ylDjtG50CAlrdWZdfYYS/juAQJprDGbpV+M+1J48SEmeGhQpvGkB6MO/rqXqdYUlRKNfFiNKo4P2HyDQu0Ji+4xWnjXniT05ZPiCXOVKSCTG73z1DhlN6oTn1r+lGNGUV3AX9JlRoJ0pDK1Z5jld7lwh+N2ez3hz+lvcM6aXhq4ExOvfFwqX4ILihpYvTuYTDXQxBcHUzCEz4eovikzsPJMW/z8ztm14CqkKeD0gp3yT7kKo8GZwcEyYP/Q6GirR9UsbR2wX+Uf9mcNuYg0xzgCBqLSmnbvmrglkHxrDmlUQOWrKVCJW6lTXaDClADK4QIKQZTmJmA1s5MNyIEMAiVF5HJHlOAWy/i4Kw5wJeXUZnnxX0JEv553FcjOjdih8MbJGhVm/1S3LWElLhGjnkPeTVb1GnZ0ejk0Pvm0f1wWQw+FrgmtW6iRF33F9r/QctKnJMnrkXEFAbH7nz1lkSAMkPJ+gow90c+S6m4DT/DRILncAnfgmNpupjLcyFfrsEbBpW9+bilM1TnQuhZQpMQn14z5fjhKH5KZ3R9Bt5jETrbkZaPnHhRaYkIk2AuO0Jnu2N8ovUnVIfwUE60n1ufQExLVnRpZT4sYe7zv4XBtB9lVGXj68mQBY6/iZwh4minVBc3eGschMhmCbTMBbk57l1fK06Co/SXOWdqrYcKvCUsWOgL7N9X2uiKP/uj/rLRWF5QQqp8/PcVAvrglg0vNzC/Ra5MZAawZMuAta0s6HDKnQ==
  template:
    metadata:
      name: multica-token
      namespace: ai
