---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-webhook-message-url
  namespace: ai
spec:
  encryptedData:
    N8N_WEBHOOK_MESSAGE_URL: AgAqYnhxkUAdPJtFOOXkZ1bVFfisJ+icGht9aRYxsdeJykSJyutBcjRxm7WQvq8Tp4F4XnIpwB0MmTiyBqiiHOeFqnd4V60BOSjVLgQRDIlt9ICTkezSMRBQiHP+mkhGgrBHWiGmPLKUyct8Q6IHO5yWMU0HI9oKildWzYRCkx9lehEVg6RLLVPY7wddxwLO0icryub1eAlVPA+Ts2FGKtAEl5ojzO1vCAF15v2ANi+Wo/ZJPa3ix8S4+5gukskGZEKhB197YYg2MPjGPIovyDTRHDvOvzm+suaV5rKLIM/Wwm8topaItWd5Kn+T5rjNFlFIglT+nR5oHzPNrlhr23gskmSnUMklSiyF0m6smGBzhRY6n+Tg+eimdVMQ/UVlVwZqw65ucgmmHY6YT7q4Nus7nL+FdDtwELS0hUl+95Uho1e2dBNB9/TACyGlKzlUjawfnrzuOFfHdYrAr1vBcgFcN7UJdGXUp27+B6oZdIfll3h+te0r1OmCvR+YUshah5qOoBn9jm87r52mCVw2o+4oQAWlla5BhATReNcHqWbBGiFHchkhC59zflzc656cRlCsRIRL62G67cWi3NKdKebuAGiw/erDaetWL5OZeu2Mj/wfSEaqmE1c7vMh4KWN45TvnknrTuP+kjZWhDeice5mFbjol045kmV4yxkhKbHAoc5tsyP1RK0GCSLaVCPSYXuUqsO3CGyIRadSq88z+V0h+Jz/VNj/5cuPXkCrSAiu2hIZkiF1OglfXBIsZgmuPtIMObJpo6SDrvGxbdwxFMwXcrn6jH/n
  template:
    metadata:
      name: n8n-webhook-message-url
      namespace: ai
    type: Opaque
