---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-webhook-message-url
  namespace: ai
spec:
  encryptedData:
    N8N_WEBHOOK_MESSAGE_URL: AgAlNWmxLLUpuk66SkZUVgH+gE2ZUOATYC09V3dLGkk0U3uLbT1FxoglHK+wfoP8hzmSgrGmLM3IqPfLveaNQ9Bx+XG49JjqI2F0t7oAEl+tHakFYziRrZk8J5UC6YAjzgHpzM5xUOHYsdok6wGi1yb/aIV+Wb+wcJy1KpTco90KpPeTnfJ5FvmeZ2O682t5xxAhN12mLSpimPtMhhVbalF9u9dGDkVgFVcIMupv4WzqHespqq30P2CvBVigw2ke0k8AO3LamumV3rHrB53VlT9qUNy8vaZEpmIMXyJmblq4Sz2f86FI6wPIf5UgaZBbFqEq/mKcg4glVlKHJx0R4Ed2/NEv2+86gegOrDw/7udPssuBkZFRk4n0HhCpxbFyHRz/WjoLSVXdiYGT4JeaIT7AgeFgAkhi5UhjClGeAyiX48cup5lCxXzKln/E1b/CG/h8jhn4118k3kHls21dAeRHX8inUMhJfQ1QXzmazIrLbEECzLGETAy408bea5/MNCdtrS+O+KkFpVQt/yQGvz3EWK/5sL6w/WAWiReI7K0GAwws+Hx/oNidJsdvgnyii1PzyrQ042Z3FOYu2EpP5F2Z/K13RbhKV0SkS22Kh8YJ+ipwWhkkrPqap4hmJ2J8w3NGQ6jSSzg6bsxvmsDBL2LWBE8KRf/q5rc0/KDSI7s28ojx15aHsM6MXAJRB8iygNq5DK9WAFU1TkeF+puxX0XmXCLiS2EV5mB0CX3AYKHp0A5iCpiCBOJC4ZoqfV2xVZ9V7QsE318r7p00aAIMdKl7kBxUvIrd
  template:
    metadata:
      name: n8n-webhook-message-url
      namespace: ai
    type: Opaque
