---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-token
  namespace: ai
spec:
  encryptedData:
    N8N_TOKEN: AgAB/JWOnFv9fbzDki7jlR9sxaAvaGKP5zt3x5vSmBOBF8Jq/302a96Dqn0XYvAQTb0ZSrldZxmo/rN6c2RCrz6bMfOqxkaeCTQBMH69JC+XczYgdGQ81qg+kTYNwWW6YcJI3AW3LoXiZJlXblyI9ggXlH9vErVoLB1Xib17uXOORPgQvSJajzPdZmxltCxMvQtKGlItnnUYrfHANuIn77WE4ZEGNNovINsoBH5rRnmhxKP5AO64vWVM5zt0xLzoE4iTtvl/Dvi+QOT3k3VzJDv6rQXrqDgqTzAUPX/zTibMoDn5uveDaFWeBONDa6NcV4teqKyQQhSS0Q2rmSxBUl3AY5vba0hags3pbP9inRZyFd9vvDNBRnsRqn/kUkp7c9PLc8gm4hHwD9Ma72+mO99Y1qi99+XnVrMquwYdZDNqoCpJUh88k2hCBOWHkTevDQiSsHW71KxhLY7MKbPyFIcexkhMncg/522Y1fj4UMZHUal3+q6E+JJrf4f0xgMIcE9X3xcv8IMfwk7klgDkYAkWxEhA3H0+trESFMSBkkfx5QLSEumpY8kBCDYjwtXIiF6KDAB84RCZk1z7BEVH6ugWzwcPVyw3ykJ+VWfoIY920c3LJzRy8jnIgn2bvDmeMSu5VMrZcCRtsXESG9CnnMVABqvZjgd2+5GcXO+Fqt6M3dOR9hSw8kj2Gry8HRrxbRdEKViEWwWkAy1Apc3cWn7Xfxxqv4n0TS/yvKzWuRIjI7Y3eIJMwvwNH2587KYRrMUAcOv0FYTpI1mLs2x5MfZCTkPPYscnlEFJukJ2uPe+p9Zg/V+c3rvSt4Y4baOTPDrgIJX1bGbrry6U8YEikl1Qdyk2ZIr4BS+5f4GyStGNmGSmRUKgf+vcR81tUF9UFZO2fLGr/ZB0KQO903t1WxDUjJAtK6J2fg8aqVjDBH0Mkt7rs7xD0cI9t48HSXYPBHQjUWijMM41rkdaffRC+WvMWHtmD1Cz9ikciDE9mWZyjedPgcQLg74MH1xFFBAPTq+rqjZrVTzqmeoVaq41hLn43zMDtmwD5UzbQmvlvGHtAw==
  template:
    metadata:
      creationTimestamp: null
      name: n8n-token
      namespace: ai
