apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: ollama
spec:
  parentRefs:
    - name: traefik-internal
      namespace: networking
  hostnames:
    - "ollama.mmontes-internal.duckdns.org"
  rules:
    - backendRefs:
        - name: ollama
          port: 11434