apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - gpu-nodegroup-localmodelnodegroup.yaml
  - qwen36-27b-nvfp4-localmodelcache.yaml
  - qwen36-27b-nvfp4-llminferenceservice.yaml
