apiVersion: serving.kserve.io/v1alpha2
kind: LLMInferenceServiceConfig
metadata:
  name: nvidia-template
spec:
  template:
    runtimeClassName: nvidia
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: nvidia.com/gpu.present
              operator: Exists
    tolerations:
    - effect: NoSchedule
      key: node.mmontes.io/type
      value: compute-xlarge
    securityContext:
      fsGroup: 1000
    containers:
      - name: main
        image: vllm/vllm-openai:v0.27.1-cu129
        securityContext:
          runAsNonRoot: false
        env:
          - name: PYTORCH_CUDA_ALLOC_CONF
            value: expandable_segments:True
        resources:
          requests:
            cpu: "1"
            memory: 4Gi
          limits:
            nvidia.com/gpu: "1"