---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hf-token
  namespace: ai
spec:
  encryptedData:
    HF_TOKEN: AgBoD/isF/e6oTRr3ETn1HWoGmL1ORhcshp2loUtYJsWQXElMWISFxD/+7USBwSAMm7v960Q00iZp2IdDbQ+dg6WL8pvYbUUh7zPzoYn76lpP8W/dD7PzxL6zIFILg2RTd5nQtghCAiBHZZ/ddM22QO5w1PITXHT6CEgohBoKSsh69n6d94xuD2Tzfp+dqeduABBLJH5Gqt5184De/kJTRKQFyajDxPoBGKOzecZQZXWs6wnCVHPJZdMW6a6HWy4MtI31vq4QeDH2tud5nywSrsOe/f9jkrW7HCAcqvpsmGYYLzaP60uIIVStLeod5X+DugPf/3CQGsKpy0dEOUG52E1SsEbADdRTiXtd7MOnXHBMrd90n4Lmm9S/tQB0PhIaPd9xUlm/KVUwtcRpuWKC8q6ODlNZyM7bqkO+rHnlM1MR5+xNO6h+RuEnSmimcKDE8Jc7v8KSh1M0b+/e2RbV5O6u3a1mkOcYPcN9EN8Jv9javXhtfFp1XQdC722+FiaTwq8uuhs2NL0QGEDbiIhafPGZHeqJMz2d6N1GDBH4izi6pNPxmUOrxcQ8AIZwOMbRZqewnpheR+tVAjQztrWaQy3FAt7Am2BMnHrqiPC2pr+aHoQpOOtuDifHrA8PQRpCKV6LJCn50M8MV5PFeW5X/hzJ7Pdd70NuheOYaSpLRvRXQlZHHa1LOs4iq6mK7NFeYzGpxOXar+0DO3BU8RN5GNAzJSl9gRU0j4se5KzX0BFYphKL3Mk
  template:
    metadata:
      creationTimestamp: null
      name: hf-token
      namespace: ai
