---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hf-token
  namespace: kserve
spec:
  encryptedData:
    HF_TOKEN: AgB1pf7rZtqCT8eHssrw6VrNJjCz3u5iRDlX3/B4998Qs88ExDWf64t7XV0chmLzArtop5UUKvGihT06SXjxnv/A3YcHhPf0BxQhOaN1/er2maV5MsCWv0UIc7Wt7EFez9/FWgaThZuwyWtpkVPWfe+QBCAWaD+x8LQ96Y8tJSbjK3mqF8JhgerlWiP3RljA79Jq+/L9/vlMXAj/BhvbwBszo4Rd1Tzas5wIcw2TkHfL+oNuzklBT31HaUOeoa8PJg2y9cgHrQlMDf2FQQ0mB2eBxJDYMwQnP4KtfTwUwFaUALe21DjT2nilam91qmxKsbmoq8p8tBtF72izw2Xg7Cl4381hTz/FCNBhTjzp2eV4JUh3mHFWls+VMKL30M8EVRP5R5ci76tFN/P4gdJIDLLlibiNQSrAZrHlwgxzCNT2L+KhWWsQRCmX8rN29Xkq3QZx6f8+t4zOsT8NP5BEfHqkdL+5gju0K2yDUjHyuQl0Gbb/7jBiUNh7PiepVkioPZd4lnDE/qxtZJxv3HgU/0GeN45qSqLE265mXOq7pIVzo4wYZUVNXjFM6bfVE17aj/qjAw0qvIX/xA6oJv1JjCx+xQQz6l2oZGH2w1lgC3DKk9R7iARPh/2e7B4ZwQsmnB9P85cBf2TzbKgmHtD8r/AuYm/EyJV1IejQlewUVFYNMxDg+VKa+N6AVGhmu7nE0l9uO3muwXH/9CdyjYhBGSVdLw1fzx8QTCfCq9uqcbBiQB4WM9d/
  template:
    metadata:
      creationTimestamp: null
      name: hf-token
      namespace: kserve
