apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: kserve-runtime-configs
spec:
  interval: 5m
  url: oci://ghcr.io/kserve/charts/kserve-runtime-configs
  ref:
    tag: "v0.17.0"
