apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: multica-backend-uploads
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-ceph
