apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: multica-secrets
  namespace: ai
spec:
  encryptedData:
    JWT_SECRET: AgCsbR3dAFKGzarg7nJmSn7edwE5F14ZKsofd8fg2KdLqwm5lHri4CCJ5Ueg3HvVGJutaOC6BNkFc/44YkPiVXiuRy/co/0o02Z41dy5vUvnvXsfrrUOuajTxXj4ZlqlC8gX3v0pd7sggKzT+2scfl6hdOSoSU7HNaMhcaHUX9qFiWhT1BbFCxCJdrN49n/pN2lWKH2chQ8ip9TdDQMa9EvXEy60rHGIWqA9VO8tjIEZQSsTFUW7iJSa5gz9/O+nJH6r3/9K/ynU1HwHSlujPjnKodlvgIJ7AiB9yMptdjJ6U8udGguLLWKPbGudU52T/n2R4bmnpaIU6fBV8rdiBEtprxQg5GCWHIPPwMy0RUT96LfAcmjp/yv44kTXJXTxL8OOIbIBl0GYZGxDUZeAL+Z5l4QblVjriFIY4KmVtsD0mudPGewmACqpGkP+vG6JDb9ATGwLpQYgVOQJMN2px/T22FvRpd36IF/9B1GXpy69rsmUqEA7eIqB9DpnRsiN9GQJA8gRlhkZMZ7mc/VhZ8n7xYKAHIST1uxKGYeTUR9MAJyT352febB1W2GrOSwLJYNnyruegNsxW0S+OdQVSQ2Xd610n8XWBlhpwGOYgxaznarzpu2i31UO3wMqJhxoftPO7HXnXwym3mC/vUpTHiXtDXLrHf+HKydtU+FoJczNGwgE5CRBkek9gqOe7onQ2ECZ6H5/rknAfuKhNQYjplampCbnB6ExONYYQ7ttOt4Ws3y0N67jDiH1XCHrojdSLddwgwBLPjBTlpyJYGYq48CS
    DATABASE_URL: AgAAcsmyyaAfiK1S4iPDAji2Lxw/Zza09qCyaaRa2Lolw66tdEQyhQ/M3ZZuM0c0BJp6VriWRFBaYMxS62Uhm9ej6nEka4c7FTW5KzuMyTopZWeTR4VqewdeYBqTd55DJbbkJkFeeOv6TtvNQ7DoyR5RIxYG/+ZB0FWYMnHC/DF9RLUtz7T5WIzEJHL8iY0FHuNo0oQc8jLITqfBfFbJOpL8/NI3l7jISyPY37tnCRqaSYydrHO2FTINNa1p4ncxP1MTMhpIsW9H+qlr41gOf715kjOwJj5kHgjUDog/NGWNYslZ07Q4JH7F5Otjd84oFAoyzpUwaYG/OSZ6AWvDhZvD0V7clJejkhXWdy/bMArP6A5Ix9t9ZYKqka6pB4YDZD3NKEddE2IPJin5VsXIBmBZHFicuqwKlJLcjf8yCnIpFoYeyhoPHeq7m2JtGYc+cSOe6RJQMoqMrwImirBDL939Iyq9TS++qL9wr6+nSGfV1A2AKuLbohBq2ew4qodj0iJllEQMAFcHjgxMKi+LBUwwuMUFlfP+lk593JQWdOQp3beCODcKFLWxJnCTOMV+ryJRDbjpMcb/w9IpYGJPiD/mTwuP+nytu/9zD1dRV1cmEZ5/UtdaaTDhT1JbKhkjwszx7QyVeSsAy4PbkZlkK6Sy0kl99h43lA57/j0mUv+H9gNarceopXbIfVrVM1/U/zFy8WZipYm3IC2KtZXacVqAZHHDEHS1viY8f/brOswFjFPH7BgDuYpQn2l/dzbyEufFQECgMfR3Mre+yIiFDhmeO23eeR+B79oImGcXpvuA0lJ5HZ+iV1o0JA==
    RESEND_API_KEY: ""
    GOOGLE_CLIENT_SECRET: ""
    CLOUDFRONT_PRIVATE_KEY: ""
    MULTICA_DEV_VERIFICATION_CODE: ""
  template:
    metadata:
      creationTimestamp: null
      name: multica-secrets
      namespace: ai
