apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: multica
spec:
  sourcePVC: multica-backend-uploads
  trigger:
    # schedule: "0 1 * * *"
    manual: multica-2
  restic:
    repository: restic-multica
    retain:
      daily: 7
    pruneIntervalDays: 14
    unlock: multica-1
    copyMethod: Clone
    moverResources:
      requests:
        cpu: 1
        memory: 300Mi
      limits:
        memory: 4Gi
    cacheCapacity: 5Gi
    cacheAccessModes:
      - ReadWriteOnce
