apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: multica
spec:
  chartRef:
    kind: OCIRepository
    name: multica
  interval: 10m
  values:
    existingSecret: multica
    postgres:
      external:
        enabled: true
    backend:
      uploads:
        persistence:
          enabled: true
          size: 5Gi
          storageClass: rook-ceph
          accessModes:
            - ReadWriteOnce
      config:
        appUrl: https://multica.mmontes-internal.duckdns.org
        frontendOrigin: https://multica.mmontes-internal.duckdns.org
        googleRedirectUri: https://multica.mmontes-internal.duckdns.org/auth/callback
        localUploadBaseUrl: https://multica-api.mmontes-internal.duckdns.org
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 1Gi
    frontend:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 1Gi
    ingress:
      enabled: false
    monitoring:
      prometheusRule:
        enabled: true