apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: multica
spec:
  interval: 5m
  url: oci://ghcr.io/multica-ai/charts/multica
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: "0.4.36"
