apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - llamacpp-configmap.yaml
  - llamacpp-httproute.yaml
  - llamacpp-service.yaml
  - llamacpp-statefulset.yaml
  # TODO: Metrics disabled, as Prometheus scrapes will awake the models
  # See: https://github.com/ggml-org/llama.cpp/issues/20227
  # - llamacpp-servicemonitor.yaml