apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - llamacpp-configmap.yaml
  - llamacpp-httproute.yaml
  - llamacpp-service.yaml
  - llamacpp-servicemonitor.yaml
  - llamacpp-statefulset.yaml