apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: llamacpp
spec:
  replicas: 1
  serviceName: llamacpp
  selector:
    matchLabels:
      app: llamacpp
  template:
    metadata:
      labels:
        app: llamacpp
    spec:
      runtimeClassName: nvidia
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.present
                operator: Exists
      tolerations:
      - effect: NoSchedule
        key: node.mmontes.io/type
        value: compute-xlarge

      initContainers:
      - name: init
        image: ghcr.io/ggml-org/llama.cpp:full-cuda13-b8496
        env:
        - name: LLAMA_CACHE
          value: /models
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token
              key: HF_TOKEN
        command:
          - /bin/bash
        args:
          - /config/init.sh
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        - name: models
          mountPath: /models
        resources:
          requests:
            cpu: "1"
            memory: 2Gi
          limits:
            memory: 4Gi
  
      containers:
      - name: llama-server
        image: ghcr.io/ggml-org/llama.cpp:full-cuda13-b8496
        env:
        - name: LLAMA_CACHE
          value: /models

        # SERVER:
        # See:
        # https://github.com/ggml-org/llama.cpp/tree/master/tools/server
        # https://github.com/ggml-org/llama.cpp/blob/master/.devops/tools.sh
        # args:
        #   - --server
        #   - --models-dir
        #   - /models
        #   - --models-preset
        #   - /config/models.ini
        #   - --models-max
        #   - "1"
        #   - --models-autoload
        #   - --sleep-idle-seconds
        #   - "600"
        #   - --n-gpu-layers
        #   - "999"
        #   - --fit
        #   - "off"
        #   - --flash-attn
        #   - "on"
        #   - --no-mmap
        #   - --host
        #   - 0.0.0.0
        #   - --port
        #   - "8080"
          # TODO: Metrics disabled, as Prometheus scrapes will awake the models
          # See: https://github.com/ggml-org/llama.cpp/issues/20227
          # - --metrics

        # BENCHMARK:
        # See:
        # https://github.com/ggml-org/llama.cpp/tree/master/tools/llama-bench
        # https://github.com/ggml-org/llama.cpp/blob/master/.devops/tools.sh
        # https://github.com/ggml-org/llama.cpp/discussions/15396
        command:
          - /bin/bash
          - -c
        args:
          - |
            echo "Starting llama-bench..."
            /app/tools.sh \
              --bench \
              --model "/models/unsloth_Qwen3.5-35B-A3B-GGUF_Qwen3.5-35B-A3B-MXFP4_MOE.gguf" \
              --threads 1 \
              --n-gpu-layers 999 \
              --fit off \
              --flash-attn on \
              --ctx-size 49152 \
              --cache-type-k q8_0 \
              --cache-type-v q8_0 \
              --batch-size 2048 \
              --ubatch-size 2048 \
              --n-prompt 2048,8192,16384,32768 \
              --progress || true
            echo "Benchmark finished"
            sleep infinity

        ports:
        - containerPort: 8080
          name: api
        resources:
          requests:
            cpu: "1"
            memory: 2Gi
          limits:
            memory: 16Gi
            nvidia.com/gpu: "1"
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        - name: models
          mountPath: /models
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 10

      volumes:
      - name: config
        configMap:
          name: llamacpp
          defaultMode: 0777

  volumeClaimTemplates:
  - metadata:
      name: models
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 300Gi
      storageClassName: topolvm