---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hf-token
  namespace: ai
spec:
  encryptedData:
    HF_TOKEN: AgAQ2zyalBtUD62RjYKma8vZ8WHFYEUzFeKz45gmdOkbOpQ7bkRPwkofloD2GSzKSArG0FvEJqSfMFjFtf0xd7Bn/aNkFNaEb8ccvaLGIVgoCddPR8tQHdw1XKs0I/itCOvHIhtCL8br3vEiFuquzNU5YCOwcWHSkFYhAbpkScWzj4tZ37jMxhUce990MbiciR9KWRFpOaGEwppqINUheVcxXnBWrtsWSy7OZp6WFrE1hZXwrwXYgmYtUEgF777khECDWiange1WOAr5MbpfO2SRPMLsWuka/oqWhIoAEzrQ0Mxb1RdGHa3XSzzgG+ToyBdNvM4CHCK7rUzRxWaFCNYAlsJZQK8+WtEKJPUYj8LIY6cdNeQ0EpVmeHDnokOc+6z3hZMH1ngcQwYsTgyGrAqg4w4Mcv/9ePT4JyQVFteRuOVPwq/Cexg0HzZVfTY/alGW00SlK18sZZsdbEC9gXI79MUXGRZwiU4YYMXmHviSHCPamJ6tm8dnWgqtjpsxn+rpv5aoZbu3tmeKPMoLKmmAmb2t8dDj2lhHBcHJolBVm3faFc5Ug/dVlMm5YQMWEqBc0P/+sQvwMfhPWmc1ULz3JckwQeCzaqD5s14MAHIaWvAcV6NdxTSLRkHk2JF3jibCIhUSvR5zhWMNrKH7pELxT3iwPX0zPvrVph3Pq5AYSqMzVPGT1APrIS9iJRWROdtb+8DbBXZgAAGmi1Lc9crFzQdKIvVs4d9xGg+w6angfzJpL1pU
  template:
    metadata:
      creationTimestamp: null
      name: hf-token
      namespace: ai
