---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: photoprism-mmontes
  namespace: media
spec:
  encryptedData:
    DB_PASSWORD: AgBshMVWjb4rM6PaXiIVLj12uBmqbj/xMeq9BCdY+zNh/0kJ9VCZyhxvstl1iETZtqM6ozb0ZuYo9F5VN7i5WLVwmA+nAkY3BA8KHAaWXSlllVHk6N3Z80PFLZXE3X9I2GbZeT5vEr40QmjfY1Z3FWGraah3Hheysfq804TV4wK4QgjAeCA4un8GYYkyIMNalAOGtPffoLULwektg6w8pNqPj/9X4P/65z1JfmfuqhCkx/x1W1WN1rLKBzcc2Bo8ITzsLzaoJaB3etnNUxwO8glqvfQIo/VITl5adjghpP5Q15OVKwsY1DoKTFkRieNWFQGUHxk1jHPTUM7zEYbDmXfF1aknWKYn9Jn5aKEwvc9a2D7Eqhqdtq8oyuCtmotfLn+TKWgTxZa7m/B5ffBfBtf3uyc709Uwfflbo0k3b7K3XgFc5zrzn3VnM7o477KCyHyINhQfG4Qxc0lfNOlRmzChlFGq5ufQF9sN9yjeLtGrS6yIHJZ2056ffw1unUxxV1JKgdySyCDMu/An39MaA/7z1Sm6lFO3tuz7iJpkByNGafzv6MNYTKcQIVHcInTDULlq8qR1uCTqiMHokA7UV9CI+z3XaaSSep4JNbgi+XpGq5xfCxkCTclR5Hbn8raAl1UF4rTqLuAfeEXr4RrE1+JRWp1QW7YhAlYcPO6n7gP3IKUG+dv6uzf6m5TKO7pSLhmtXtlSqNNMNdReGfA9gJtWdQlddQ==
    DB_USER: AgBgc/Nup8FCYPDtzwhDxKPDOSRA+HBFhmZfVyH8c1KAaT+qPMPmD4bEk+23QMq9er696Lxj3D2ngrpVu6pyYLplY2OcmJ610KH46zVgU3UANtioyYEvGi4eZ1szBrYlT0mjGmLPhfPU+L5nvhMFqoaPbxkLeLXwkVaY9HSNqXmLXJNa37FFCz/HAECYaPaFA5cknlVOOcEAuXZ8ehXz28O7IDvXyizi8bzAhlBqwB1WJkIQxFE0Ah5TJHq0lEr6qLW2TVMgP0relYsJ8j2lTgl1ZFrOYUlrHDxPLtIbBCGNrJ4r2+oSzp0eiRnqhq0NRY3+qipk7KPoU1xRr6jncottde6OCbHYfD3kK+6USL/Kex5ITXwIIxEIKDUtT44xLwMibuRTajXMz/atgdWNiICMg3y29Bb40gG+YQ2CJpZV1UB58bsgGy0mpg5T/cXLLrUslu25lRvfV0a7jvPvUnkLF62v2DHZTQxQaDqoLRYuZX+I3tmAmA78W6JR8C/VACqOZ3+DjXge2ZBGhrGCLAjGrnnHY3Na2OqhQ195tBGv48sGtRaNz71PRBmL8K0WNqY6aNJs0ZmAdMvcCNsSzrBfI2C2QwnMv6K5AG5ZYI25ysJhbxAhM/q+Rd5mgOGJjsHWscTLpK4pGfCu7J8fEx/67h/ACMkwzGtGx6OhI3KihYhvc3JmwlxKKsz3iXNru1GzLiZuto2Q
  template:
    metadata:
      creationTimestamp: null
      name: photoprism-mmontes
      namespace: media
