apiVersion: serving.kserve.io/v1alpha2
kind: LLMInferenceService
metadata:
  name: facebook-opt
  namespace: kserve
spec:
  model:
    name: facebook/opt-125m
    uri: hf://facebook/opt-125m

  replicas: 1

  template:
    runtimeClassName: nvidia
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: nvidia.com/gpu.present
              operator: Exists
    tolerations:
    - effect: NoSchedule
      key: node.mmontes.io/type
      value: compute-xlarge
    containers:
      - name: main
        image: vllm/vllm-openai:cu130-nightly
        resources:
          requests:
            cpu: "500m"
            memory: 4Gi
          limits:
            memory: 8Gi
            nvidia.com/gpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: facebook-test
  namespace: kserve
spec:
  ports:
  - appProtocol: http
    name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/name: facebook-opt
    app.kubernetes.io/part-of: llminferenceservice
    kserve.io/component: workload
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: facebook-opt
  namespace: kserve
spec:
  hostnames:
  - facebook-test.mmontes-internal.duckdns.org
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: traefik-internal
    namespace: networking
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: facebook-test
      port: 8000
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
