apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opencode
spec:
  serviceName: opencode
  replicas: 1
  selector:
    matchLabels:
      app: opencode
  template:
    metadata:
      labels:
        app: opencode
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1111
      runtimeClassName: nvidia
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.present
                operator: Exists
      tolerations:
      - effect: NoSchedule
        key: node.mmontes.io/type
        value: compute-xlarge
      volumes:
        - name: opencode
          configMap:
            name: opencode
        - name: run
          emptyDir: {}

      initContainers:
        - name: sync
          image: ghcr.io/mmontes11/opencode:048f51a
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              if [ $(ls -A /home/mmontes | grep -v "lost+found" | wc -l) -eq 0 ]; then
                echo "PVC is empty. Initializing..."
                rsync -rlptDq /opt/template/ /home/mmontes/
              fi              
              chown -R 1111:1111 /home/mmontes/
              mkdir -p /home/mmontes/.ssh
              chmod 700 /home/mmontes/.ssh
              chmod 600 /home/mmontes/.ssh/* || true
              chmod 644 /home/mmontes/.ssh/*.pub  || true
              chmod 644 /home/mmontes/.ssh/known_hosts|| true
              chmod 644 /home/mmontes/.ssh/config || true 
              echo "Sync complete."
          volumeMounts:
            - name: home
              mountPath: /home/mmontes

      containers:
        - name: opencode
          image: ghcr.io/mmontes11/opencode:048f51a
          securityContext:
            runAsUser: 1111
            runAsGroup: 1111
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gh-token
                  key: GITHUB_TOKEN
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token
                  key: HF_TOKEN
            - name: N8N_TOKEN
              valueFrom:
                secretKeyRef:
                  name: n8n-token
                  key: N8N_TOKEN
            - name: DOCKER_HOST
              value: unix:///var/run/docker.sock
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              nvidia.com/gpu: "1"
          ports:
            - containerPort: 4096
          volumeMounts:
            - name: home
              mountPath: /home/mmontes
            - name: opencode
              mountPath: /home/mmontes/.config/opencode/opencode.json
              subPath: opencode.json
            - name: run
              mountPath: /var/run
        - name: dind
          image: docker:29.4.0-dind
          args:
            - --group=1111
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
          volumeMounts:
            - name: run
              mountPath: /var/run
            - name: docker
              mountPath: /var/lib/docker
  volumeClaimTemplates:
    - metadata:
        name: home
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "topolvm"
        resources:
          requests:
            storage: 100Gi
    - metadata:
        name: docker
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "topolvm"
        resources:
          requests:
            storage: 100Gi