apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - llama-qwen35-35b-q3-httproute.yaml
  - llama-qwen35-35b-q3-service.yaml
  - llama-qwen35-35b-q3-servicemonitor.yaml
  - llama-qwen35-35b-q3-statefulset.yaml