apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - mcp-n8n-deployment.yaml
  - mcp-n8n-httproute.yaml
  - mcp-n8n-service.yaml
  - n8n-token-sealedsecret.yaml
