---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-token
  namespace: ai
spec:
  encryptedData:
    N8N_TOKEN: AgB0Ul1BtZPOhQI9NgPHsWuwAQbd41mBLJTQFAyV6R6fjodUsMagTc1iQF6an3deqzQeFnjaeyTL8H6LNK851qDiQqLMg6kWdMynPe0kHUXBzV0kZPjfma7dFtBq2u6ApIXFgIREVGFknpoefV622rmVQq34ZTjvwYuYMQK63X96Kc/2ENJlW2dXb7/RZMSWikmHxj/R6KiU05CTYBHIjy6KvPXvD5vqjly8b6IULdMd9CE/0YOoh4y0PkrGsFf/hgqYzb4n1ACNZpq4qzqdx9uN73bjU0zrwkZbWGzMMHKPFgyNp58rPMIoyNUsRBew9rHJ9NXvtAlv78K8ui9oYmy+y2mNcNDfZZ0iHWWXyWmTX4yVTfCY4cqS9qouqbV7FqjacUlocJHAsp/NZLePln5xuUM27vqOMB6zhJXrv3eyHVxGvSMPenva3VasAlhJGsZ47m/V83e2J9DGBkbuIHfMKIFCnYKXh+8pkSwBg+NKkeKtUAt7eoAqvlBzEvApuPjKVkICXpOyQlmJnAuWta59XNwC+ji3nulXdL4a5iLZtC6gdaotHwa1WZZ7kL9h4pHhFgQUETiQQVvw1YQ8cSlL/YpJmcT2JvWOxARnmjv/U0fzpsWSODrgcvxRO/sWz1wFBi4dFAANIHXtJoDM530BKBhF4NEHAi+VJ7CEwWY+Jg4SjCqsLwNh+zQLzRT+RG+pWZ8pf8negEGRq7d8aJ9E8mzyBsJ6O/wU7TggjDX2VTX7gAOtg6J7UaihOF4jaDn4muUF/7F1XoJnWkxe7TzZP+gjby47ki7qiJVzHsMR1gzUBrq/Aj7tvzqpLTPsi+ZR4tMDhcwxurRwoQ0Aen8h3GW4xLQUblANm6XE8bbQDeGjax3xkcos9SZefbFM3murmHk8IMJ2ANoEDrJcEtGXRBgMVRX8FSBQezK16b/tHH/RdMc95+5+SPpLDnl99/xuoGDKqQACopj6gfcPEsJdBIMh5w+2qWOfMEKT1jAExo66vg5E15QQACWzOfXF2Lp0mO+Uw613R6WjqygosA1zs+W/wmoXODldMrk=
  template:
    metadata:
      creationTimestamp: null
      name: n8n-token
      namespace: ai
