apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: llm
spec:
  parentRefs:
    - name: traefik-internal
      namespace: networking
  hostnames:
    - "llm.mmontes-internal.duckdns.org"
  rules:
    - backendRefs:
        - name: open-webui
          port: 80