apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: open-webui
spec:
  sourcePVC: open-webui
  trigger:
    schedule: "0 2 * * *"
    # manual: open-webui-2
  restic:
    repository: restic-open-webui
    retain:
      daily: 7
    pruneIntervalDays: 14
    unlock: open-webui-1
    copyMethod: Clone
    moverResources:
      requests:
        cpu: 1
        memory: 300Mi
      limits:
        memory: 4Gi
    cacheCapacity: 5Gi
    cacheAccessModes:
      - ReadWriteOnce
    customCA:
      secretName: homelab-bundle
      key: ca.crt
