apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: open-webui
spec:
  chart:
    spec:
      chart: open-webui
      sourceRef:
        kind: HelmRepository
        name: open-webui
      version: "8.19.0"
  interval: 1h0m0s
  values:
    ollama:
      enabled: false
    ollamaUrls:
      - http://ollama:11434
    persistence:
      enabled: true
      size: 2Gi
      accessModes:
        - ReadWriteOnce
      storageClass: rook-ceph
    service:
      type: ClusterIP
      port: 80