apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: open-webui
spec:
  trigger:
    # schedule: "0 4 * * *"
    manual: open-webui-1
  restic:
    repository: restic-open-webui
    destinationPVC: open-webui
    copyMethod: Snapshot
    moverResources:
      requests:
        cpu: 1
        memory: 300Mi
      limits:
        memory: 4Gi
    cacheCapacity: 5Gi
    cacheAccessModes:
      - ReadWriteOnce
    customCA:
      secretName: homelab-bundle
      key: ca.crt
