apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: open-webui
spec:
  chart:
    spec:
      chart: open-webui
      sourceRef:
        kind: HelmRepository
        name: open-webui
      version: "10.2.1"
  interval: 1h0m0s
  values:
    ollama:
      enabled: false
    ollamaUrls:
      - http://ollama:11434
    pipelines:
      enabled: false
    persistence:
      enabled: true
      existingClaim: open-webui
    service:
      type: ClusterIP
      port: 80
    extraEnvVars:
      - name: WEBUI_NAME
        value: 草泥马🦙
      - name: BYPASS_MODEL_ACCESS_CONTROL
        value: "true"